server:
  port: 2525
spring:
  application:
    name: DROP-DOWN
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/vadkte
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    
    show-sql: true
    hibernate:
      ddl-auto: update